Extend daily ci timeout
siliconcompiler/siliconcompiler pull request #1280
Opened 2023-02-08 20:10 UTC by WRansohoff

* Extend timeout to 40 minutes (picorv32+RAM functional test adds ~15min)
* Annotate `remote_test` marker: markers let you pass arguments into pytest fixtures, but pytest prints warnings if it encounters a marker which is not defined.

[Verification test run](https://github.com/siliconcompiler/siliconcompiler/actions/runs/4127983359)

2023-02-08 20:50 UTC, gadfort approved these changes

2023-02-08 20:52 UTC, gadfort requested changes
Make sure the remote test isn't part of the quick CI (its timed out)

2023-02-09 13:07 UTC, gadfort commented
@WRansohoff while you are fixing the Quick CI, could you add a test specific timeout (like we did to the show tests) to the really slow one?

2023-02-09 18:22 UTC, WRansohoff commented
Sure, thanks for the suggestion.

2023-02-09 21:37 UTC, gadfort approved these changes
Why did the timeout on quick CI change?

2023-02-09 21:40 UTC, WRansohoff commented on .github/workflows/on_push_tests.yml
> +    timeout-minutes: 20
Y'know what, maybe it wasn't. The last quick tests completed in a little under 9 minutes. I wonder why it timed out in the last run - maybe a blip, but it looks like the remote tests probably weren't responsible.

2023-02-09 21:41 UTC, WRansohoff commented
Another idea: we could omit the local picorv32+RAM example, since including both versions effectively doubles its runtime. The remote one would have caught the manifest-merging bug, but the local one is largely similar to the other `asicflow` example tests, and `heartbeat_padring` already covers using macros in a local build.

2023-02-09 21:48 UTC, gadfort commented on .github/workflows/on_push_tests.yml
> +    timeout-minutes: 20
yeah, thats what I'm thinking. I'd prefer to keep it at 15 for now.

2023-02-09 22:27 UTC, gadfort commented
@WRansohoff sounds good.

2023-02-09 22:48 UTC, WRansohoff commented
Look promising, the 3.10 batch is back down to ~25 minutes:

https://github.com/siliconcompiler/siliconcompiler/actions/runs/4138755396

2023-02-09 23:13 UTC, gadfort approved these changes

2023-02-10 01:15 UTC, merged