Updated installation instructions
siliconcompiler/siliconcompiler pull request #1321
Opened 2023-02-23 23:59 UTC by aulihant

Followed steps for offline install and developer's installation to make sure it works with Ubuntu 20.04

2023-02-24 13:31 UTC, gadfort requested changes
There are two error when building:
siliconcompiler/docs/user_guide/installation.rst:123: ERROR: Content block expected for the "note" directive; none found.
siliconcompiler/docs/user_guide/installation.rst:246: WARNING: Inline target start-string without end-string.

2023-02-24 13:31 UTC, gadfort commented on docs/user_guide/installation.rst
> +3. You can install directly from the git repository (best for developers).
Add links to each section describing these

2023-02-24 13:31 UTC, gadfort commented on docs/user_guide/installation.rst
> +SiliconCompiler can be installed directly from `pypi.org <https://pypi.org>`_ using pip. Activate your `Python Virtual Environment <https://docs.python.org/3/library/venv.html>`_ and follow the instr
no need for the "(identical for Windows, Linux, and macOS)." statement

2023-02-24 13:31 UTC, gadfort commented on docs/user_guide/installation.rst
> - (venv) python -c "import siliconcompiler;print(siliconcompiler.__version__)"
do we want to show an example output from this command?

2023-02-24 13:31 UTC, gadfort commented on docs/user_guide/installation.rst
> +To install from a bundle, create a Python virtual environment following the instructions above, then perform the following commands.
link back to that section

2023-02-24 13:31 UTC, gadfort commented on docs/user_guide/installation.rst
> +This only installs the SC build system offline. Before you can start running SiliconCompiler, you will also need to make sure you have installed external PDKs and tools required to build (synthesis,
I don't think the PDKs are in the wheel builds, so this applies to pip installs too.

2023-02-24 13:31 UTC, gadfort commented on docs/user_guide/installation.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^
On line 205, make sc-configure a :ref:`sc-configure` and same for sc-ping

2023-02-24 13:31 UTC, gadfort commented on docs/user_guide/installation.rst
> +If you wish to run locally, you will need to install some external tool dependencies to start. Take a look at `External Tools`_ to start with Surelog, Yosys, OpenRoad and KLayout as a minimum to run.
I think this should be clarified to say that those tools are required for as a minimum for a ASIC flow

2023-02-24 13:31 UTC, gadfort commented on docs/user_guide/installation.rst
> +.. _External Tools:
Change last line from ending with "here" to make the "tools directory" the link

2023-02-24 13:31 UTC, gadfort commented on docs/user_guide/installation.rst
> +See the _`Quickstart <https://docs.siliconcompiler.com/en/latest/user_guide/quickstart.html>`_ section to get more details on what you're running.
This should just be a :ref:quickstart

2023-02-24 13:31 UTC, gadfort commented on docs/user_guide/installation.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Add a link to the remote processing section for more information

2023-02-27 22:18 UTC, aulihant commented on docs/user_guide/installation.rst
> +Confirm your Installation
@gadfort this is an example of the breaking out a section that is common to all methods of installation. This prevents copy/pasting of instruction thus reducing the likelihood of divergence. But it also potentially makes instructions more confusing for someone who wants to just read all the way through without skipping around. Do you have any thoughts on this?

2023-02-27 22:19 UTC, aulihant commented
@gadfort I incorporated your requested changes which are really straightforward. The two comments which are left unresolved are related to general documentation flow. Some instructions will be the same for different install methods (e.g. checking your installation, needing PDKs and external tools installed), so we can either create common instruction for these, or copy and paste the same instruction into different sections.

2023-02-28 01:58 UTC, gadfort requested changes
Looks good, we can chat about the last couple of things tomorrow morning

2023-02-28 01:58 UTC, gadfort commented on docs/user_guide/installation_confirm_version.rst
> +To confirm your installation:
Can you move these into a subdirectory like docs/user_guide/installation/?

2023-02-28 01:58 UTC, gadfort commented on docs/user_guide/installation_prep_path.rst
> +To prepare your path and get set up with examples and PDKs to run:
Can you move these into a subdirectory like docs/user_guide/installation/?

2023-02-28 01:58 UTC, gadfort commented on docs/user_guide/installation.rst
> +   If you need to set up PDKs and tools and have an internet connection, you can run the following steps.
I think you should add this to the prep_path as well.

2023-02-28 01:58 UTC, gadfort commented on docs/user_guide/installation.rst
> +Skip to `Run local`_.
Should this be a link to Run instead of Run local?

2023-02-28 01:58 UTC, gadfort commented on docs/user_guide/installation.rst
> +Run Remote with Cloud Access
Lets discuss this one tomorrow

2023-02-28 01:58 UTC, gadfort commented on docs/user_guide/installation.rst
> +To view IC layout files (DEF, GDSII) we recommend installing the open source multi-platform 'klayout' viewer (available for Windows, Linux, and macOS). Installation instructions for klayout can be fo
You can just make this a link to klayout with :ref:`klayout`

2023-02-28 01:58 UTC, gadfort commented on docs/user_guide/installation.rst
>  To test the klayout installation, run the 'sc-show' to display the 'heartbeat' layout:
Ref to sc-show

2023-02-28 21:39 UTC, gadfort approved these changes

2023-02-28 21:42 UTC, merged