Gabriel/toggle switch to checkbox
siliconcompiler/siliconcompiler pull request #1779
Opened 2023-07-18 17:13 UTC by GabrielAguirre1

I wanted a toggle for the user to be able to show the manifest unfiltered. I have had trouble using the current toggle (a widget we import) rendering on unselected tabs. I'm not sure how to fix this problem, so while I figure that out, I think a good solution is to use a checkbox that is native to Streamlit (which avoids this error). A consequence of this decision is that all toggles should really be checkboxes - it's silly to have them mismatched.

Here is a photo of the checkboxes where the toggles were:
<img width="1187" alt="Flowgraph" src="https://github.com/siliconcompiler/siliconcompiler/assets/80078690/81300330-e2b2-46fa-8a62-10e77062d9e6">

Here is a photo of the checkbox to switch the manifest from filtered to unfiltered:
<img width="1344" alt="Manifest Tree" src="https://github.com/siliconcompiler/siliconcompiler/assets/80078690/dcd1bcaa-6d51-4cc6-bfe7-e08b0a6a9bd8">

I have tested the functionality of the checkboxes and the functionality of the search bars given the unfiltered manifest.

2023-07-19 08:24 UTC, troibe commented on siliconcompiler/report/streamlit_viewer.py
> +        streamlit.markdown('')
Do you need this twice for alignment?

2023-07-19 08:29 UTC, troibe commented
So the current behaviour is that there is still some filtering going on even if the user doesn't search for any keys or values?
What is getting filtered and why?

2023-07-19 08:32 UTC, troibe commented on siliconcompiler/report/streamlit_viewer.py
> +def show_manifest(chip, manifest, max_num_of_keys_to_show=20):
Wouldn't it make more sense to have filtering enabled/disabled in your `make_manifest` function?
If this is way easier feel free to leave it though.

2023-07-19 13:17 UTC, GabrielAguirre1 commented on siliconcompiler/report/streamlit_viewer.py
> +        streamlit.markdown('')
Unfortunately, yes.

2023-07-19 13:25 UTC, GabrielAguirre1 commented
> So the current behaviour is that there is still some filtering going on even if the user doesn't search for any keys or values? What is getting filtered and why?

There are a few places where the manifest is simplified. Some of the keys are labeled as 'default', and those branches are essentially duplicate information, so I remove those branches. Some of the key follow the pattern `manifest_branch[step][index]`, and those have been concatenated to `manifest_branch[step + index]`. Finally, the leaves hold about 7 keys and only one of the values of those keys is useful to the user, so I've simplified the leaf to that value.

2023-07-19 13:28 UTC, gadfort commented
@GabrielAguirre1 I think the phrase "filtered" is a bit misleading, you are showing an unfiltered manifest (but it's been cleaned up a bit), so maybe "raw" is a better term?

2023-07-19 13:32 UTC, GabrielAguirre1 commented
> @GabrielAguirre1 I think the phrase "filtered" is a bit misleading, you are showing an unfiltered manifest (but it's been cleaned up a bit), so maybe "raw" is a better term?

Sounds good. Just changed it.

2023-07-19 13:38 UTC, troibe commented on siliconcompiler/report/streamlit_viewer.py
> +def show_manifest(chip, manifest, max_num_of_keys_to_show=20):
I guess it depends on whether you want the user to allow filtering the "raw" manifest as well or just the "clean" manifest.
@gadfort Would filtering on the "raw" manifest provide any value to the user or is it too overwhelming?

2023-07-19 13:41 UTC, troibe commented on siliconcompiler/report/streamlit_viewer.py
> +def show_manifest(chip, manifest, max_num_of_keys_to_show=20):
Nevermind filtering comes later so this works.

2023-07-20 14:11 UTC, gadfort requested changes
Please figure out the flowgraph hiding and moving of the Raw switch.
You should add `.., help=''` to the checkboxes to provide more context about what they are supposed to it.

2023-07-20 14:11 UTC, gadfort commented on siliconcompiler/report/streamlit_viewer.py
> +    if streamlit.checkbox('raw'):
can you move the checkbox up next to to the search bars?

2023-07-20 14:11 UTC, gadfort commented on siliconcompiler/report/streamlit_viewer.py
> +    fg_toggle = not streamlit.checkbox('Hide')
When this is hidden it still says Hide, but it's not clear what it is doing. This should probably be changed to indicate this is the flowgraph somehow.

2023-07-20 21:10 UTC, GabrielAguirre1 commented
I made the changes suggested.

Here is what the Hide flowgraph checkbox looks like. And the '?' is added for the tooltip. I'm not sure how I feel about it yet, but I'm not sure if I can change it at the moment. 
<img width="263" alt="Screen Shot 2023-07-20 at 5 04 52 PM" src="https://github.com/siliconcompiler/siliconcompiler/assets/80078690/c9c30e13-b755-4f4e-a966-f6388514a7fc">

Here is the checkbox for getting the raw manifest. I implemented logic so that the checkbox doesn't take up too much space on a larger monitor. 
<img width="1328" alt="Manifest Tree" src="https://github.com/siliconcompiler/siliconcompiler/assets/80078690/68eef9c4-7783-4675-8589-be58ad54b8c3">

2023-07-31 14:29 UTC, GabrielAguirre1 commented
Here are the two fixes @gadfort and I spoke about. 

Here is the toggle when the flowgraph is hidden.
<img width="1328" alt="Data Metrics" src="https://github.com/siliconcompiler/siliconcompiler/assets/80078690/1c85a6c9-dcd4-4e24-8803-d0249c05d340">

Here is the toggle when the flowgraph is not hidden.
<img width="1332" alt="Flowgraph" src="https://github.com/siliconcompiler/siliconcompiler/assets/80078690/a656690d-0d58-4041-b613-81db2efb0b17">

Here is "Raw Manifest" --> "Raw manifest".
<img width="208" alt="Screen Shot 2023-07-31 at 10 20 35 AM" src="https://github.com/siliconcompiler/siliconcompiler/assets/80078690/4a5f7683-4faa-4051-a343-9cc57d3abca5">

2023-07-31 14:48 UTC, gadfort approved these changes

2023-07-31 14:53 UTC, merged