Add docs scripts to ci
siliconcompiler/siliconcompiler pull request #1815
Opened 2023-07-31 13:05 UTC by troibe

Currently we don't test the examples in our user guide.
This adds them to our CI.

The following examples were omitted because they are not actually used anywhere in the docs:
- [challenge_nda.py](https://github.com/siliconcompiler/siliconcompiler/blob/main/docs/user_guide/examples/challenge_nda.py)
- [challenge_nsquared.py](https://github.com/siliconcompiler/siliconcompiler/blob/main/docs/user_guide/examples/challenge_nsquared.py)
- [pattern_forkjoin.py](https://github.com/siliconcompiler/siliconcompiler/blob/main/docs/user_guide/examples/pattern_forkjoin.py)
- [pattern_general.py](https://github.com/siliconcompiler/siliconcompiler/blob/main/docs/user_guide/examples/pattern_general.py)
- [pattern_pipeline.py](https://github.com/siliconcompiler/siliconcompiler/blob/main/docs/user_guide/examples/pattern_pipeline.py)

2023-07-31 13:17 UTC, gadfort requested changes
I don't think you need to return the fixture setup and can just make the changes there. Check the EDA flag, if the run needs tooling then we need to mark it that way, otherwise that mark is not needed.

2023-07-31 13:17 UTC, gadfort commented on tests/docs/conftest.py
> +    return setup
is this needed? couldn't you just do the monkeypatch'ing here?

2023-07-31 13:17 UTC, gadfort commented on tests/docs/test_flowgraph_doe.py
> +@pytest.mark.eda
does this require any EDA tools?

2023-07-31 13:17 UTC, gadfort commented on tests/docs/test_write_manifest.py
> +@pytest.mark.eda
eda is not needed for this one

2023-07-31 13:19 UTC, gadfort commented
I think the unused ones are used to build some images that are used in presentations, etc, maybe you can move them to a different directory for image generation so its clear what they are.

2023-07-31 13:56 UTC, troibe commented
> I think the unused ones are used to build some images that are used in presentations, etc, maybe you can move them to a different directory for image generation so its clear what they are.

Oh ok I just saw that. It's creates the images in the `docs/user_guide/_images` folder.

2023-08-01 13:22 UTC, gadfort approved these changes
LGTM

2023-08-03 21:12 UTC, merged