Add two more Slurm states which may be reported during normal operation
siliconcompiler/siliconcompiler pull request #1869
Opened 2023-08-15 15:21 UTC by WRansohoff

We have seen some intermittent failures in the Slurm tests, which appeared to be caused by the scheduler module encountering unexpected states when it looks at the job queue.

This change adds two more non-error states which are uncommon, but may be reported during normal Slurm runs.

2023-08-15 15:27 UTC, gadfort requested changes

2023-08-15 15:27 UTC, gadfort commented on siliconcompiler/scheduler.py
> +           'STAGE_OUT' in jobout:
is there a definitive list of these somewhere? if so, lets add a link to it and make sure all are accounted for.
Also the watchdog timer is gone, so we can remove that code too.

2023-08-15 17:40 UTC, gadfort requested changes
It seems like there are a lot more code slurm can report, I think it would be prudent to add them so we dont' have to do this one by one

2023-08-17 17:44 UTC, WRansohoff commented
Good point - I've updated the logic to track all possible Slurm job states, split into 'active' and 'inactive' categories.

2023-08-17 21:24 UTC, gadfort approved these changes

2023-08-18 01:27 UTC, merged