Add prune
siliconcompiler/siliconcompiler pull request #2008
Opened 2023-09-29 18:29 UTC by troibe

**What?**
Extends the functionality in: https://github.com/siliconcompiler/siliconcompiler/pull/1976
The naming is `prune` instead of `exclude` as that is what was the outcome of the siliconcompiler meeting two weeks ago.

**Testing:**
I implemented the specification as best as I could understand it.
The most important part to me and what required changes is that the correctness of the paths in the flowgraph is based on reaching all final steps but within those final steps it doesn't matter how many nodes (at least one) was reached.

2023-09-29 18:30 UTC, troibe commented
I'm happy about any further testing we can add to this one as the per node flowgraph combined with the per step success is still about confusing to me.

2023-09-29 18:42 UTC, gadfort requested changes
Overall looks good, just needs to switch the type form str to (str, str) in the schema (and fix where it's used)

2023-09-29 18:42 UTC, gadfort commented on siliconcompiler/schema/schema_cfg.py
> +            sctype='[str]',
i think we would want this to be [(str, str)] instead

2023-09-29 18:42 UTC, gadfort commented on siliconcompiler/schema/schema_cfg.py
> +                "cli: -prune 'syn0'",
-prune 'syn 0'

2023-09-29 18:42 UTC, gadfort commented on siliconcompiler/schema/schema_cfg.py
> +                "api: chip.set('option', 'prune', 'syn0')"],
chip.set('option', 'prune', ('syn', '0'))

2023-09-29 18:52 UTC, gadfort commented on siliconcompiler/schema/schema_cfg.py
> +            shorthelp="Prune branches starting with",
Prune flowgraph...

2023-10-01 20:32 UTC, gadfort commented
https://github.com/siliconcompiler/siliconcompiler/actions/runs/6372810647/job/17295978850

2023-10-04 01:32 UTC, nmoroze reviewed
Overall looks good! I think it might be good to add a test case that pruning one node that feeds into a builtin min/max still allows the rest of the flow to proceed without that node.

2023-10-04 01:32 UTC, nmoroze commented on siliconcompiler/core.py
> +        if self._unreachable_steps_to_execute(flow):
I think you can reuse `unreachable_steps` here

2023-10-04 01:32 UTC, nmoroze commented on siliconcompiler/core.py
> +                        f'to {current_node} are missing. '
nit: are -> is

2023-10-05 23:08 UTC, merged