Link server test
siliconcompiler/siliconcompiler pull request #2106
Opened 2023-11-21 10:22 UTC by troibe

Enabled the server test again and linked the `ref` and `sc-ref`.

2023-11-21 10:23 UTC, troibe commented
`ref` needs to be changed back to main before merging.

2023-11-21 15:31 UTC, gadfort requested changes

2023-11-21 15:31 UTC, gadfort commented on .github/workflows/server_ci.yml
> -      - main
can we make that on pull_request? and switch this be in the tools ci so the tools image is correctly built before it's needed?

2023-11-26 16:59 UTC, gadfort approved these changes

2023-11-26 16:59 UTC, merged