Stdout eda option
siliconcompiler/siliconcompiler pull request #961
Opened 2022-03-27 07:38 UTC by suppamax

Following up #944 - a proposal for a new option for `eda` configuration, to notify that the tool outputs the result to STDOUT.

2022-04-13 10:36 UTC, suppamax commented
I can take care of that, but unfortunately I cannot do anything before Easter.

2022-04-13 14:05 UTC, nmoroze commented
Sounds good, thanks!

2022-05-02 17:38 UTC, nmoroze commented
@suppamax thanks for updating this! I just wanted to double-check, is the updated version ready for review?

2022-05-02 17:51 UTC, suppamax commented
It is.

2022-05-03 02:58 UTC, nmoroze requested changes
Great, this is looking awesome. We're getting closer! I left a few inline comments, mostly around style (e.g. renaming variables to be consistent with our `snake_case` convention).

Thanks!

2022-05-03 02:58 UTC, nmoroze commented on siliconcompiler/core.py
> +                stdoutFile = ''
Use snake case for variable names, e.g. `stdout_file`.

2022-05-03 02:58 UTC, nmoroze commented on siliconcompiler/core.py
> +                    stdoutFile = step + "." + self.get('eda', tool, 'stdout', step, index, 'suffix')
These lines are getting a little long, would recommend storing `suffix` in a temp variable to keep them shorter, e.g.:

```suggestion
                    suffix = self.get('eda', tool, 'stdout', step, index, 'suffix')
                    stdout_file = step + "." + suffix
```

2022-05-03 02:58 UTC, nmoroze commented on siliconcompiler/core.py
> +                        stderrFile = subprocess.STDOUT
What is the purpose of these lines?

2022-05-03 03:00 UTC, nmoroze commented on siliconcompiler/schema.py
> +            Defines where to direct the output generated over stdout.""")
Would be nice to add one more sentence with list of supported options

2022-05-05 17:46 UTC, aolofsson commented
This is a really nice addition! Thank you @suppamax for flagging the issue, the great implementation, and patience in working with us on the iterations!

2022-05-05 17:46 UTC, merged